services:
  postgres:
    image: postgres:16-alpine
    container_name: tummy-tikki-db
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tummytikki_orders
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - tummy-network

volumes:
  postgres_data:

networks:
  tummy-network:
    driver: bridge
